# Exception

scala中所有的异常，可以处理，也可以不处理

```scala
object Demo1 {
  def main(args: Array[String]): Unit = {
    try{
      var a = 1/0
      
      throw new FileNotFoundException("aaa")
      
    }catch {
      case e:ArithmeticException=>println("exception")
      case e1:FileNotFoundException=>println(e1.getMessage)
    }finally {
      println("释放资源")
    }
  }
  
  //抛异常类型
  @throws(classOf[RuntimeException])
  @throws(classOf[IndexOutOfBoundsException])
  def fun: Unit ={
    //方法调用者可以捕获，也可以不捕获
    println("111111111")
    
  }
  
}
```